const newbieMap = [
  // 0 line
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: false,
    road_S: false,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: false,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: false,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: false,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  // 1 line
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: false,
    road_S: false,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "mountains",
    token: 10,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "pasture",
    token: 2,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "forest",
    token: 9,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  // 2 line
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: false,
    road_S: false,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "fields",
    token: 12,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "hills",
    token: 6,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "pasture",
    token: 4,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "hills",
    token: 10,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  // 3 line
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: false,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  {
    type: "fields",
    token: 9,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "forest",
    token: 11,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "desert",
    token: 0,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: true,
    harbor: false,
  },
  {
    type: "forest",
    token: 3,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "mountains",
    token: 8,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: false,
    road_N: false,
    road_W: true,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  // 4 line
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: false,
    road_W: false,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  {
    type: "forest",
    token: 8,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "mountains",
    token: 3,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "fields",
    token: 4,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "pasture",
    token: 5,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  // 5 line
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: false,
    road_W: false,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  {
    type: "hills",
    token: 5,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "fields",
    token: 6,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "pasture",
    token: 11,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: true,
    settlement_S: true,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: true,
    road_W: true,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  // 6 line
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: false,
    road_W: false,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: true,
    road_W: false,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: true,
    road_W: false,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
  {
    type: "sea",
    token: 0,
    settlement_N: true,
    road_N: true,
    road_W: false,
    road_S: false,
    settlement_S: false,
    robber: false,
    harbor: false,
  },
]

export default newbieMap;
